name: Watch Upstream Commits

on:
  schedule:
    - cron: '43 1 * * *' # Runs once a day at 1:43 AM UTC
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  check-upstream-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Get latest commit SHA from neodrama/github-drama
        id: get_commit
        run: |
          LATEST_SHA=$(curl -s https://api.github.com/repos/neodrama/github-drama/commits/main | jq -r .sha)
          echo "latest_sha=$LATEST_SHA" >> $GITHUB_OUTPUT

      - name: Get last seen SHA
        id: get_last_sha
        run: |
          LAST_SHA=$(gh issue list --search "Upstream SHA:" --state all --json title --jq '.[0].title' | grep -oE '[a-f0-9]{40}' || echo '')
          echo "last_sha=$LAST_SHA" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compare SHAs and open issue if new commit
        if: steps.get_commit.outputs.latest_sha != steps.get_last_sha.outputs.last_sha
        uses: actions/github-script@v7
        with:
          script: |
            const latestSha = process.env.LATEST_SHA = '${{ steps.get_commit.outputs.latest_sha }}';
            const lastSha = process.env.LAST_SHA = '${{ steps.get_last_sha.outputs.last_sha }}';
            if (latestSha && latestSha !== lastSha) {
              github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Upstream SHA: ${latestSha}`,
                body: `A new commit (${latestSha}) was pushed to neodrama/github-drama.\n\nSee: https://github.com/neodrama/github-drama/commit/${latestSha}`
              });
            }
